const gulp = require('gulp')
const connect = require('gulp-connect')
const sourcemaps = require('gulp-sourcemaps')
const rename = require('gulp-rename')
const GulpUglify = require('gulp-uglify')
const sass = require('gulp-sass')(require('sass'))
gulp.task('sass', (res) => {
  gulp.src('sass/*.scss').pipe(sourcemaps.init()).pipe(sass()).pipe(sourcemaps.write('./')).pipe(gulp.dest('./CSS')).pipe(connect.reload())
  res()
})
